name: Deploy to production

on:
  push:
    branches:
      - main  # Change this to your production branch.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Deploy to production
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << EOF
            rm -rf rapidagent-docs
            git clone https://x-access-token:${{ secrets.ORG_GH_TOKEN }}@github.com/Rapidstartupio/rapidagent-docs.git
            cd rapidagent-docs
            lsof -i :3333 | awk 'NR>1 {print $2}' | xargs kill -9
            nohup mintlify dev --port 3333 > mintlify_output.log 2>&1 &
          EOF
